pat=new Pattern();
pat.document=document;
var makePattern = function() {
pat.paper.clear();
scale=pat.scale;
    myMeasurements={}
var sideLength=document.getElementById('sideLengthSlider').value*scale;
var waist=document.getElementById('waistSlider').value*scale;
var waistToKnee=document.getElementById('waistToKneeSlider').value*scale;
pat.addPoint("A",8.6 *scale,9.7 *scale)
pat.rightPoint("B","A",120.0 *scale);
pat.downPoint("C","B",120.0 *scale);
pat.alongPoint("D","B","C",waist/4.0);
pat.leftPoint("O","D",pat.distance("B","D")/3.0);
pat.leftPoint("E","B",waist/2.0-2.0 *scale);
pat.circleLSIntersectionPoint("F","O","C","B",sideLength);
pat.downPoint("F2","D",waist/4.0);
pat.displacementPoint("T","F",-125.0 *scale,12.0 *scale);
pat.perpendicularBisectorPoint("S","O","E",-4.0 *scale);
pat.alongPoint("V","E","T",waistToKnee);
pat.perpendicularPoint("V2","T","V",-(22.0 *scale));
pat.perpendicularPoint("I","V","V2",-(-6.0 *scale));
pat.perpendicularPoint("J","V","V2",-(6.0 *scale));
pat.rightPoint("fA","B",12.0 *scale);
pat.rightPoint("fB","fA",pat.distance("A","B"));
pat.downPoint("fC","fB",pat.distance("B","C"));
pat.downPoint("f2","fB",2.0 *scale);
pat.downPoint("f5","fB",5.0 *scale);
pat.downPoint("f7","fB",7.0 *scale);
pat.leftPoint("fE","f2",44.0 *scale);
pat.leftPoint("fO","f5",19.0 *scale);
pat.leftPoint("fO2","f7",4.0 *scale);
pat.circleLSIntersectionPoint("fF","fO2","fB","fC",sideLength);
pat.alongPoint("fU","fB","fF",waist/2.0+12.0 *scale);
pat.leftPoint("fU2","fU",37.0 *scale);
pat.circleLSIntersectionPoint("fZ","fE","fA","fB",15.0 *scale);
pat.displacementPoint("fZ2","fZ",-9.0 *scale,0.5 *scale);
pat.perpendicularBisectorPoint("fZ3","fZ","fZ2",-20.0 *scale);
pat.circleLineIntersectionPoint("fY","fZ2","fA",6.9 *scale,0.0);
pat.leftPoint("fL","fF",120.0 *scale);
pat.upPoint("fT","fL",3.0 *scale);
pat.alongPoint("fV","fY","fT",waistToKnee+6.0 *scale);
pat.perpendicularPoint("fS","fT","fV",-(22.0 *scale));
pat.perpendicularPoint("fI","fV","fS",-(-6.0 *scale));
pat.perpendicularPoint("fJ","fV","fS",-(6.0 *scale));
pat.printPoints();
pat.line("F","F2");
pat.displacedQuad("F2","O",pat.distance("F2","O")/2.0,-(1.0 *scale));
pat.displacedQuad("T","F",pat.distance("T","F")/2.0,-(4.8 *scale));
pat.line("E","T");
pat.fittedQuad("E","S","O");
pat.displacedQuad("I","E",pat.distance("I","E")/2.0,-(-3.0 *scale));
pat.displacedQuad("J","T",pat.distance("J","T")/2.0,-(3.0 *scale));
pat.line("J","V");
pat.line("I","V");
pat.displacedQuad("fO","fO2",pat.distance("fO","fO2")/2.0,-(1.0 *scale));
pat.displacedQuad("fE","fU2",pat.distance("fE","fU2")/2.0,-(-2.4 *scale));
pat.displacedQuad("fO","fU2",pat.distance("fO","fU2")/2.0,-(1.0 *scale));
pat.line("fZ","fE");
pat.displacedQuad("fZ","fZ3",pat.distance("fZ","fZ3")/2.0,-(1.0 *scale));
pat.displacedQuad("fZ2","fZ3",pat.distance("fZ2","fZ3")/2.0,-(-1.5 *scale));
pat.line("fY","fT");
pat.line("fY","fZ2");
pat.displacedQuad("fO2","fU",pat.distance("fO2","fU")/2.0,-(-1.5 *scale));
pat.line("fU","fF");
pat.displacedQuad("fT","fF",pat.distance("fT","fF")/2.0,-(2.5 *scale));
pat.displacedQuad("fI","fY",pat.distance("fI","fY")/2.0,-(-2.0 *scale));
pat.displacedQuad("fJ","fT",pat.distance("fJ","fT")/2.0,-(2.0 *scale));
pat.line("fI","fV");
pat.line("fJ","fV");
displaydistance(document);
}
makePattern(true);
wireUpScale(document);
wireUpControl(document,'sideLength');
wireUpControl(document,'waist');
wireUpControl(document,'waistToKnee');
wireUpDistance(document);
